const fs = require('fs');
const path = require('path');
module.exports = ({SPECIES, page, SITE, esc}) => {
  const root = path.join(__dirname, '..');
  const base = page(SPECIES[0]);
  const siteContent = require('./site-content');
  function render({title, description, url, schema, content}) {
    return base
      .replace(/<!--[\s\S]*?-->/, '<!-- Generated by scripts/build-hubs.js. -->')
      .replace(/<title>[\s\S]*?<\/title>/, `<title>${esc(title)}</title>`)
      .replace(/<meta name="description"[^>]+>/, `<meta name="description" content="${esc(description)}" />`)
      .replace(/<link rel="canonical"[^>]+>/, `<link rel="canonical" href="${SITE}${url}" />`)
      .replace(/<meta property="og:type"[^>]+>/, '<meta property="og:type" content="website" />')
      .replace(/<meta property="og:title"[^>]+>/, `<meta property="og:title" content="${esc(title)}" />`)
      .replace(/<meta property="og:description"[^>]+>/, `<meta property="og:description" content="${esc(description)}" />`)
      .replace(/<meta property="og:url"[^>]+>/, `<meta property="og:url" content="${SITE}${url}" />`)
      .replace(/<meta property="og:image"[^>]+>/, `<meta property="og:image" content="${SITE}/images/og-default.png" />`)
      .replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/, `<script type="application/ld+json">${JSON.stringify(schema, null, 2)}</script>`)
      .replace(/<main id="main">[\s\S]*?<\/main>/, `<main id="main"><div class="wrap">${content}</div></main>`);
  }
  const cards = SPECIES.map(sp => `<a class="guide-row" href="/fish/${sp.slug}"><h3>${esc(sp.name)}</h3><p>${esc(sp.description)}</p><span class="go">Read the guide →</span></a>`).join('\n');
  fs.writeFileSync(path.join(root, 'fish', 'index.html'), render({
    title: "Fish Taste & Cooking Guides | Catch 'N Bake", description: 'Choose your fish for taste, preparation, and cooking advice. Explore snook, grouper, red snapper, Pacific halibut, and more, with official fishing rule links.', url: '/fish/',
    schema: {'@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Fish Taste and Cooking Guides', url: SITE + '/fish/', mainEntity: {'@type': 'ItemList', itemListElement: SPECIES.map((sp, i) => ({'@type': 'ListItem', position: i + 1, name: sp.name, url: `${SITE}/fish/${sp.slug}`}))}},
    content: `<nav aria-label="Breadcrumb"><a href="/">Home</a> / Fish Guides</nav><h1>Fish Taste and Cooking Guides</h1><p class="intro">Choose your fish to learn what it tastes like, how to prepare it, and ways to cook it. Each guide links to official fishing rules so you can check your catch before planning dinner.</p><h2>Find your species</h2><div class="guides">${cards}</div><h2>Start with the catch</h2><p>Keep a clear photo and your trip notes together in <a href="/">Catch 'N Bake</a>. Confirm the species and official harvest rules before keeping a fish, then use the guide for preparation ideas.</p><p><a href="/about#editorial">About our guides</a></p>`
  }));
  fs.writeFileSync(path.join(root, 'about.html'), render({
    title: "About Catch 'N Bake & Our Fish Guides", description: 'Catch N Bake helps anglers identify fish, remember trips, and find ways to cook their catch. Learn how we prepare species guides, use original catch photos, and handle corrections.', url: '/about',
    schema: {'@context': 'https://schema.org', '@type': 'AboutPage', name: "About Catch 'N Bake", url: SITE + '/about', about: {'@type': 'Organization', name: "Catch 'N Bake LLC", url: SITE + '/'}},
    content: `<nav aria-label="Breadcrumb"><a href="/">Home</a> / About</nav><h1>About Catch 'N Bake</h1><p class="intro">Catch 'N Bake helps anglers identify a catch, remember the trip, and find a way to cook their fish.</p><p>The app brings photo identification, a catch journal, species recipes, and a fishing community into one place. The <a href="/fish/">field guides</a> give you a place to start before you download.</p><h2 id="editorial">How we prepare these guides</h2><p>We link to fisheries agencies for identification and harvest information. We use food safety sources for handling and cooking temperatures. Sources appear at the end of each guide.</p><p>Cooking sections offer preparation ideas. We do not label them as tested recipes or publish invented ratings. Taste varies with the fish, handling, and preparation.</p><p>Catch photos come from our own fishing trips where identified. We label illustrative meal photos separately. An article can appear without a species photo while we prepare an original image.</p><p>We show an updated date when we revise a guide. That date does not guarantee that fishing rules remain unchanged. Check the official agency page for your location and trip date.</p><h2>Send a correction</h2><p>If you spot a species error, outdated link, or unclear instruction, <a href="/support">contact us</a> with the page address and the detail to review.</p><h2>Explore the app</h2><p><a href="/">See Catch 'N Bake</a> or <a href="/fish/">browse the fish guides</a>.</p>`
  }));
  fs.writeFileSync(path.join(root, 'updates.html'), render(siteContent.updates));
  // Update shared navigation on generated and static pages without changing their layout.
  const files = fs.readdirSync(root).filter(f => f.endsWith('.html') && !['verify.html', '404.html'].includes(f)).map(f => path.join(root, f))
    .concat(fs.readdirSync(path.join(root, 'fish')).filter(f => f.endsWith('.html')).map(f => path.join(root, 'fish', f)));
  for (const file of files) {
    let html = fs.readFileSync(file, 'utf8');
    html = html.replaceAll('href="/#guides"', 'href="/fish/"');
    html = html.replace(/\s*<a class="all" href="\/fish\/">All guides →<\/a>/g, '');
    html = html.replace(/(<a href="\/fish\/spanish-mackerel">Spanish Mackerel<\/a>)(?!\s*<a href="\/fish\/red-snapper")/g, '$1\n<a href="/fish/red-snapper">American Red Snapper</a>\n<a href="/fish/halibut">Pacific Halibut</a>\n<a href="/fish/">All fish guides</a>');
    html = html.replace(/(<a href="\/support">Support<\/a>)(?!\s*<a href="\/about")/g, '$1\n<a href="/about">About</a>');
    html = html.replace(/<footer\b[\s\S]*?<\/footer>/g, footer => footer.includes('href="/updates"') ? footer : footer.replace('<a href="/about">About</a>', '<a href="/about">About</a>\n<a href="/#faq">FAQ</a>\n<a href="/updates">What\'s new</a>'));
    fs.writeFileSync(file, html);
  }
  const homeFile = path.join(root, 'index.html');
  let home = fs.readFileSync(homeFile, 'utf8');
  home = home.replace(/\s*<div class="guide-row teaser"[\s\S]*?<\/div>/, '');
  home = home.replace(/(<div class="guides[^\"]*">)[\s\S]*?(<\/div>)/, `$1\n${cards}\n$2`);
  const faq = `<!-- APP FAQ START -->\n${siteContent.homeFaq()}\n<!-- APP FAQ END -->`;
  home = home.includes('<!-- APP FAQ START -->')
    ? home.replace(/<!-- APP FAQ START -->[\s\S]*?<!-- APP FAQ END -->/, faq)
    : home.replace('<!-- ============ FINAL CTA ============ -->', faq + '\n\n<!-- ============ FINAL CTA ============ -->');
  fs.writeFileSync(homeFile, home);
  const staticPages = [['/', '2026-09-14'], ['/fish/', '2026-09-09'], ['/about', '2026-09-09'], ['/updates', '2026-09-14'], ['/support', '2026-09-10'], ...['privacy','terms','guidelines'].map(p => [`/${p}`, '2026-07-03'])];
  const urls = [...staticPages, ...SPECIES.map(sp => [`/fish/${sp.slug}`, sp.modified || sp.published || '2026-07-03'])];
  fs.writeFileSync(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(([url, date]) => `  <url><loc>${SITE}${url}</loc><lastmod>${date}</lastmod></url>`).join('\n')}\n</urlset>\n`);
  require('./build-blog')();
};
